module.exports = {
  addOrgManager: require('./addOrgManager'),
  canCreateOrg: require('./canCreateOrganization'),
  createOrganization: require('./createOrganization'),
  doesBaseExist: require('./doesBaseExist'),
  doesOrgExist: require('./doesOrgExist'),
  doesUserExist: require('./doesUserExist'),
  getAdminData: require('./getAdminData'),
  getAllUserData: require('./getAllDataAssociatedWithUser'),
  isAdmin: require('./isAdmin'),
  isBaseCodeUnique: require('./isBaseCodeUnique'),
  isBaseManager: require('./isBaseManager'),
  isBaseNameUnique: require('./isBaseNameUnique'),
  isBasePhoneNumberUnique: require('./isBasePhoneNumberUnique'),
  isOrgManager: require('./isOrgManager'),
  isSubscribed: require('./isSubscribed'),
  isSubscriptionCodeUnique: require('./isSubscriptionCodeUnique'),
  isUserEmailUnique: require('./isUserEmailUnique'),
  subscriptionCodeIsUnique: require('./subscriptionCodeIsUnique')
};
